// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/finance/pembayaran": {
            "get": {
                "description": "Fetches full payment database logs for finance preview.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keuangan"
                ],
                "summary": "Get All Pembayaran",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TPembayaranPremi"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Endpoint untuk mencatat pembayaran premi/nota dinas.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keuangan"
                ],
                "summary": "Record Pembayaran Premi",
                "parameters": [
                    {
                        "description": "Data Pembayaran",
                        "name": "pembayaran",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TPembayaranPremi"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TPembayaranPremi"
                        }
                    }
                }
            }
        },
        "/finance/refund": {
            "post": {
                "description": "Endpoint untuk pencatatan Refund Premi.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Keuangan"
                ],
                "summary": "Record Refund Premi",
                "parameters": [
                    {
                        "description": "Data Refund",
                        "name": "refund",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TRefundPremi"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TRefundPremi"
                        }
                    }
                }
            }
        },
        "/peserta": {
            "get": {
                "description": "Fetches all active and inactive participant data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta"
                ],
                "summary": "Get all peserta",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.TPeserta"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new participant record for YKP manual input",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta"
                ],
                "summary": "Create new peserta",
                "parameters": [
                    {
                        "description": "Data Peserta",
                        "name": "peserta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TPeserta"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.TPeserta"
                        }
                    }
                }
            }
        },
        "/peserta/{id}": {
            "get": {
                "description": "Fetch comprehensive details of a specific participant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta"
                ],
                "summary": "Get peserta by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Peserta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TPeserta"
                        }
                    }
                }
            },
            "put": {
                "description": "Update participant details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta"
                ],
                "summary": "Update peserta",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID Peserta",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Data Peserta",
                        "name": "peserta",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.TPeserta"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TPeserta"
                        }
                    }
                }
            }
        },
        "/upload/peserta": {
            "post": {
                "description": "Mengunggah dan mem-parsing file XLSX berisi data peserta secara massal.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Peserta"
                ],
                "summary": "Upload Excel Data Kepesertaan (HC BRI)",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Excel file (.xlsx)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.MKelasProspens": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "models.MKelompokProspens": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "models.MStatusBpjs": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "models.MStatusBrilife": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kode": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                }
            }
        },
        "models.TPembayaranPremi": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "file_bukti_bayar": {
                    "type": "string"
                },
                "id_status_pembayaran": {
                    "type": "string"
                },
                "no_nota_dinas": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                },
                "total_premi": {
                    "type": "number"
                }
            }
        },
        "models.TPeserta": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id_kelas": {
                    "type": "integer"
                },
                "id_kelompok": {
                    "type": "integer"
                },
                "id_peserta": {
                    "type": "string"
                },
                "jenis_mutasi": {
                    "type": "string"
                },
                "kelas": {
                    "$ref": "#/definitions/models.MKelasProspens"
                },
                "kelompok": {
                    "$ref": "#/definitions/models.MKelompokProspens"
                },
                "nama_peserta": {
                    "type": "string"
                },
                "nik_bri": {
                    "type": "string"
                },
                "no_kartu_brilife": {
                    "type": "string"
                },
                "status_bpjs": {
                    "$ref": "#/definitions/models.MStatusBpjs"
                },
                "status_bpjs_id": {
                    "type": "integer"
                },
                "status_brilife": {
                    "$ref": "#/definitions/models.MStatusBrilife"
                },
                "status_brilife_id": {
                    "type": "integer"
                },
                "tgl_phk": {
                    "type": "string"
                },
                "tmt_pertanggungan": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.TRefundPremi": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "file_invoice_refund": {
                    "type": "string"
                },
                "id_refund": {
                    "type": "string"
                },
                "nominal_refund": {
                    "type": "number"
                },
                "status_jurnal": {
                    "type": "string"
                },
                "tanggal": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "YKP BRI Prospens API",
	Description:      "Backend API Service for YKP BRI Prospens System Maker-Checker-Signer",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
